### ISSUE TITLE
502 Bad Gateway problem

### ISSUE THREAD

**Issue by TheGloriousHacker** [mattermost/docker#47]
Maybe I'm just too stupid or too unexperienced with docker to get this to run OR it is a bug.

I use this slight changed docker-compose.yml to get it all running and mattermost is the only service creating the 502 Error.

`
version: '3'

services:

  nginx-proxy:
    image: jwilder/nginx-proxy:latest
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
    container_name: kollektiv-proxy
    networks:
      - kollektiv-cloud
    ports:
      - 80:80
      - 443:443
    volumes:
      - /data/kollektiv-cloud/nginx/vhost.d:/etc/nginx/vhost.d:rw
      - /data/kollektiv-cloud/nginx/html:/usr/share/nginx/html:rw
      - /data/kollektiv-cloud/nginx/certs:/etc/nginx/certs:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:v1.12
    container_name: kollektiv-letsencrypt
    depends_on:
      - nginx-proxy
    networks:
      - kollektiv-cloud
    volumes:
      - /data/kollektiv-cloud/nginx/vhost.d:/etc/nginx/vhost.d:rw
      - /data/kollektiv-cloud/nginx/html:/usr/share/nginx/html:rw
      - /data/kollektiv-cloud/nginx/certs:/etc/nginx/certs:rw
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

  nextcloud-mysql:
    image: mariadb:10.4.10
    container_name: nextcloud-mysql
    networks:
      - kollektiv-cloud
    volumes:
      - /data/kollektiv-cloud/mysql:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=****
      - MYSQL_PASSWORD=****
      - MYSQL_DATABASE=kollektiv-db
      - MYSQL_USER=kollektiv-user
    restart: unless-stopped

  wordpress-mysql:
    image: mysql:5.7
    volumes:
      - /data/kollektiv-cloud/mysql-wordpress:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=****
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=****
    container_name: wordpress_db
    networks: 
      - kollektiv-cloud

  postgres:
    container_name: postgres_mattermost
    image: postgres:13-alpine
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    pids_limit: 100
    read_only: true
    tmpfs:
      - /tmp
      - /var/run/postgresql
    volumes:
      -  /data/kollektiv-cloud/var/lib/postgresql/data:/var/lib/postgresql/data
    environment:

      # necessay Postgres options/variables
      - POSTGRES_USER=mmuser
      - POSTGRES_PASSWORD=****
      - POSTGRES_DB=mattermost

  nextcloud-app:
    image: nextcloud:17.0.1-apache
    container_name: nextcloud-app
    networks:
      - kollektiv-cloud
    depends_on:
      - letsencrypt
      - nginx-proxy
      - nextcloud-mysql
    volumes:
      - /data/kollektiv-cloud/app/html:/var/www/html
      - /data/kollektiv-cloud/app/config:/var/www/html/config
      - /data/kollektiv-cloud/app/custom_apps:/var/www/html/custom_apps
      - /data/kollektiv-cloud/app/data:/var/www/html/data
      - /data/kollektiv-cloud/app/themes:/var/www/html/themes
      - /etc/localtime:/etc/localtime:ro
    environment:
      - VIRTUAL_HOST=next.kollektiv.cloud
      - LETSENCRYPT_HOST=next.kollektiv.cloud
      - LETSENCRYPT_EMAIL=luca.batz18@gmail.com
    restart: unless-stopped

  wordpress:
    depends_on:
      - wordpress-mysql
      - letsencrypt
      - nginx-proxy
    image: wordpress:latest
    restart: always
    environment:
      - VIRTUAL_HOST=kollektiv.cloud
      - LETSENCRYPT_HOST=kollektiv.cloud
      - LETSENCRYPT_EMAIL=luca.batz18@gmail.com
      - WORDPRESS_DB_HOST=wordpress-mysql
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=****
      - WORDPRESS_DB_NAME=wordpress
    container_name: wordpress
    networks:
      - kollektiv-cloud

  mattermost:
    depends_on:
      - postgres
      - letsencrypt
      - nginx-proxy
    container_name: mattermost
    image: mattermost/mattermost-team-edition:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    pids_limit: 200
    read_only: true
    tmpfs:
      - /tmp
    volumes:
      - ./volumes/app/mattermost/config:/mattermost/config:rw
      - ./volumes/app/mattermost/data:/mattermost/data:rw
      - ./volumes/app/mattermost/logs:/mattermost/logs:rw
      - ./volumes/app/mattermost/plugins:/mattermost/plugins:rw
      - ./volumes/app/mattermost/client/plugins:/mattermost/client/plugins:rw
    environment:
      VIRTUAL_HOST: chat.kollektiv.cloud
      LETSENCRYPT_HOST: chat.kollektiv.cloud
      LETSENCRYPT_EMAIL: luca.batz18@gmail.com

      # necessary Mattermost options/variables (see env.example)
      MM_SQLSETTINGS_DRIVERNAME: postgres
      MM_SQLSETTINGS_DATASOURCE: postgres://mmuser:****@postgres/mattermost?sslmode=disable&connect_timeout=10

      # additional settings
      MM_SERVICESETTINGS_SITEURL: https://chat.kollektiv.cloud

networks:
  kollektiv-cloud:
`

**Comment by phleba** [comment]
Hello, we had a similar issues with our own external nginx (based . Besides some problems we see with the docker-compose above like missing network definitions, for our system the main problem was that we had to define the Environment variable `VIRTUAL_HOST `.

See here: https://github.com/nginx-proxy/nginx-proxy/issues/413

It seems like the mattermost docker container is internally exposing additional ports...? Because normally, the base nginx_proxy should default to the exposed port (here: 8065) which for some reasons is not forwarded to nginx upstream as referenced here: 

https://github.com/nginx-proxy/nginx-proxy#virtual-ports

Here our `docker-compse.yml` for references

``` yml
(...)
mattermost:
       depends_on:
         - postgres
    container_name: mattermost
    image: mattermost/${MATTERMOST_IMAGE}:${MATTERMOST_IMAGE_TAG}
    restart: ${RESTART_POLICY}
    #expose:
    #  - 8065
    ports:
      - 8065:8065 #from the without-nginx.yml 
    security_opt:
      - no-new-privileges:true
    pids_limit: 200
    read_only: ${MATTERMOST_CONTAINER_READONLY}
    tmpfs:
      - /tmp
 volumes:
      - ${MATTERMOST_CONFIG_PATH}:/mattermost/config:rw
      - ${MATTERMOST_DATA_PATH}:/mattermost/data:rw
      - ${MATTERMOST_LOGS_PATH}:/mattermost/logs:rw
      - ${MATTERMOST_PLUGINS_PATH}:/mattermost/plugins:rw
      - ${MATTERMOST_CLIENT_PLUGINS_PATH}:/mattermost/client/plugins:rw
      - ${MATTERMOST_BLEVE_INDEXES_PATH}:/mattermost/bleve-indexes:rw
      # When you want to use SSO with GitLab, you have to add the cert pki chain of GitLab inside Alpine
      # to avoid Token request failed: certificate signed by unknown authority 
      # (link: https://github.com/mattermost/mattermost-server/issues/13059 and https://github.com/mattermost/docker/$
      # - ${GITLAB_PKI_CHAIN_PATH}:/etc/ssl/certs/pki_chain.pem:ro
    environment:
      # timezone inside container
      - TZ
      # necessary Mattermost options/variables (see env.example)
      - MM_SQLSETTINGS_DRIVERNAME
      - MM_SQLSETTINGS_DATASOURCE
      # necessary for bleve
      - MM_BLEVESETTINGS_INDEXDIR
      # additional settings
      - MM_SERVICESETTINGS_SITEURL
      ## THIS IS KULTURHAUS KRAMS
      # Letsencryptstuffz
      - VIRTUAL_HOST=example.somethind.com, www.example.somethind.com
      - LETSENCRYPT_HOST=example.somethind.com, www.example.somethind.com
      - VIRTUAL_PORT=8065
    networks:
      - mattermost
      - nginx-proxy_proxynet
(...)
```
