### ISSUE TITLE
How to map the docker's PUID:PGID (2000:2000) to a host user's PUID:PGID?

### ISSUE THREAD

**Issue by R8s6** [mattermost/docker#63]
Hi,

I'm asking because in the old `mattermost-docker`'s `docker-compose.yml` file, we had:
```
...
  app:
    build:
      context: app
      args:
         - edition=team
         - PUID=2000
         - PGID=2000
```
I had customized those numbers to 1000:1000 in `mattermost/mattermost-docker`. 

And after migrating to `mattermost/docker`, I had various errors which appeared to be permission related.

So is there a way to map the UID:GID in this new docker?

Thanks!
