### ISSUE TITLE
Mattermost can't connect to postgres: password authentication failed

### ISSUE THREAD

**Issue by lecoqlibre** [mattermost/docker#75]
Hi, the mattermost service can't manage to connect to postgres, here is the result of `docker logs`:
```
{"level":"info","ts":1638953734.2359033,"caller":"app/server.go:214","msg":"Server is initializing..."}
{"level":"info","ts":1638953734.2365377,"caller":"app/web_hub.go:83","msg":"Starting websocket hubs","number_of_hubs":6}
{"level":"warn","ts":1638953734.2369666,"caller":"app/server.go:223","msg":"Sentry reporting is enabled, but SENTRY_DSN is not set. Disabling reporting."}
{"level":"info","ts":1638953734.2381017,"caller":"utils/i18n.go:90","msg":"Loaded system translations","for locale":"fr","from locale":"/mattermost/i18n/fr.json"}
{"level":"info","ts":1638953734.2580488,"caller":"sqlstore/supplier.go:235","msg":"Pinging SQL","database":"master"}
{"level":"error","ts":1638953734.2681053,"caller":"sqlstore/supplier.go:247","msg":"Failed to ping DB","error":"pq: password authentication failed for user \"mmuser\"","retrying in seconds":10}
```

But I have the postgres service running well, I can connect to it using `psql -h 127.0.0.1 -p 5433 -U mmuser mattermost` from my docker host.

I am not using `nginx` because I have already a reverse proxy, so I use the `docker-compose.without-nginx.yml` file in addition to the regular `docker-compose` file.

I have another postgres container running on my docker host, so I changed the port of the postgres service to 5433, in my `docker-compose.without-nginx.yml`:
```
version: "2.4"

services:
  postgres:
    ports:
      - ${PGPORT}:5432

  mattermost:
    ports:
      - ${APP_PORT}:8065
```

I launch the whole with `docker-compose -f docker-compose.yml -f docker-compose.without-nginx.yml up -d`.

What am I missing? Thanks!

Here is the postgres part of my .env:
```
POSTGRES_IMAGE_TAG=12.4-alpine
POSTGRES_DATA_PATH=./volumes/db/var/lib/postgresql/data

POSTGRES_USER=mmuser
POSTGRES_PASSWORD=mypassword
POSTGRES_DB=mattermost
PGPORT=5433

MM_SQLSETTINGS_DRIVERNAME=postgres
MM_SQLSETTINGS_DATASOURCE=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable&connect_timeout=10
```

`docker logs` of postgres service:
```
2021-12-08 08:54:11.679 UTC [1] LOG:  starting PostgreSQL 12.4 on x86_64-pc-linux-musl, compiled by gcc (Alpine 9.3.0) 9.3.0, 64-bit
2021-12-08 08:54:11.680 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2021-12-08 08:54:11.680 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2021-12-08 08:54:11.686 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2021-12-08 08:54:11.723 UTC [23] LOG:  database system was shut down at 2021-12-08 08:49:54 UTC
2021-12-08 08:54:11.739 UTC [1] LOG:  database system is ready to accept connections
```

**Comment by craph** [comment]
Hi, @lecoqlibre 

If your two containers are not on the same docker network it will not work.
You have to create a compose file with your both container image and link them on the same network

**Comment by lecoqlibre** [comment]
Hi @craph, the `docker inspect` command tells me that both the postgres and mattermost containers are part of the same network: `mattermost-docker_default`. This network is automatically created by the docker-compose engine so the two containers should be already linked, aren't they?

**Comment by lecoqlibre** [comment]
Sure @craph, it is basically the same as this repo:

```
# https://docs.docker.com/compose/environment-variables/

version: "2.4"

services:
  postgres:
    container_name: postgres_mattermost
    image: postgres:${POSTGRES_IMAGE_TAG}
    restart: ${RESTART_POLICY}
    security_opt:
      - no-new-privileges:true
    pids_limit: 100
    read_only: true
    tmpfs:
      - /tmp
      - /run
    volumes:
      - ${POSTGRES_DATA_PATH}:/var/lib/postgresql/data
    environment:
      # timezone inside container
      - TZ

      # necessary Postgres options/variables
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - DEFAULT_PGSOCKET_DIR

  mattermost:
    depends_on:
      - postgres
    container_name: mattermost
    image: mattermost/${MATTERMOST_IMAGE}:${MATTERMOST_IMAGE_TAG}
    restart: ${RESTART_POLICY}
    security_opt:
      - no-new-privileges:true
    pids_limit: 200
    read_only: ${MATTERMOST_CONTAINER_READONLY}
    tmpfs:
      - /tmp
    volumes:
      - ${MATTERMOST_CONFIG_PATH}:/mattermost/config:rw
      - ${MATTERMOST_DATA_PATH}:/mattermost/data:rw
      - ${MATTERMOST_LOGS_PATH}:/mattermost/logs:rw
      - ${MATTERMOST_PLUGINS_PATH}:/mattermost/plugins:rw
      - ${MATTERMOST_CLIENT_PLUGINS_PATH}:/mattermost/client/plugins:rw
    environment:
      # timezone inside container
      - TZ

      # necessary Mattermost options/variables (see env.example)
      - MM_SQLSETTINGS_DRIVERNAME
      - MM_SQLSETTINGS_DATASOURCE
```

Here is the `docker-compose.without-nginx.yml`:
```
version: "2.4"

services:
  postgres:
    ports:
      - ${PGPORT}:5432

  mattermost:
    ports:
      - ${APP_PORT}:8065
```
