### ISSUE TITLE
Could not create config file: permission denied

### ISSUE THREAD

**Issue by AlexKalopsia** [mattermost/docker#94]
Hi everyone, I am running on this issue while trying to get Mattermost to run on my machine. 

My docker-compose:

```
mattermost: 
    container_name: mattermost
    image: mattermost/mattermost-enterprise-edition:latest 
    ports:
    - 8065:8065
    volumes:
      - ${DOCKER_PATH}/mattermost/config:/mattermost/config:rw
      - ${DOCKER_PATH}/mattermost/data:/mattermost/data:rw
      - ${DOCKER_PATH}/mattermost/logs:/mattermost/logs:rw
      - ${DOCKER_PATH}/mattermost/plugins:/mattermost/plugins:rw
      - ${DOCKER_PATH}/mattermost/client-plugins:/mattermost/client/plugins:rw
      - ${DOCKER_PATH}/mattermost/bleve-indexes:/mattermost/bleve-indexes:rw
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - APP_PORT=8065
      - MM_SQLSETTINGS_DRIVERNAME=postgres
      - MM_SQLSETTINGS_DATASOURCE=postgres://${MATTERMOST_USER}:${MATTERMOST_PSW}@${IP}:5438/${MATTERMOST_DB}?sslmode=disable&connect_timeout=10
      - MM_BLEVESETTINGS_INDEXDIR=/mattermost/bleve-indexes
      - MM_SERVICESETTINGS_SITEURL=${MATTERMOST_URL}
    security_opt:
      - no-new-privileges:true
    pids_limit: 200
    read_only: false
    tmpfs:
      - /tmp
    restart: unless-stopped
    depends_on:
      - postgres
```

Once I deploy the container I get:

```
Error: failed to load configuration: could not create config file: open /mattermost/config/config.json: permission denied
Usage:
  mattermost [flags]
  mattermost [command]

Available Commands:
  completion  Generate the autocompletion script for the specified shell
  db          Commands related to the database
  export      Export data from Mattermost
  help        Help about any command
  import      Import data.
  jobserver   Start the Mattermost job server
  server      Run the Mattermost server
  version     Display version information

Flags:
  -c, --config string   Configuration file to use.
  -h, --help            help for mattermost

Use "mattermost [command] --help" for more information about a command.
```

I have found some issues from the deprecated repo (https://github.com/mattermost/mattermost-docker/issues/407) (https://github.com/mattermost/mattermost-docker/issues/544#issuecomment-873680946) that seem related to my current issue. The main difference is that the old repo would force users to manually build their image, but in this case I can't, since the image is already built. 

I have tried setting the folder permissions manually, but with no luck. 

I hope you can help me figure out how to fix this, thank you.
